- hosts: localhost
  become: true

  tasks:
  - name: delete old deployment
    command: kubectl delete -f /opt/deployment.yaml
  - name: delete old service
    command: kubectl delete -f /opt/service.yaml
  - name: create service
    command: kubectl create -f /opt/service.yaml
  - name: create dep
    command: kubectl create -f /opt/deployment.yaml

#cd /etc/ansible/hosts
#   [controller]
#     x.x.x.x
